### ISSUE TITLE
How to Use `dpstrf` for Pivoted Cholesky Decomposition

### ISSUE THREAD

**Issue by evolutics** [fommil/netlib-java#100]
I would like to use LAPACK’s [`dpstrf`](https://github.com/fommil/netlib-java/blob/master/netlib/LAPACK/dpstrf.f) to do a pivoted Cholesky decomposition of positive-semidefinite matrices. However, the function is not found via

```Scala
 com.github.fommil.netlib.LAPACK.getInstance.dpstrf
```

when calling `netlib-java` 1.1.2 from Scala. Any help would be much appreciated! Thanks.

For positive-definite matrices I already use `dpotrf`, which works very well.

**Comment by fommil** [comment]
Interesting, when was the routine added to LAPACK?

**Comment by evolutics** [comment]
From the release notes, I think that [`dpstrf` first came with LAPACK 3.2](http://www.netlib.org/lapack/lapack-3.2.html#_9_7_pivoted_cholesky) in 2008.

**Comment by fommil** [comment]
OK, well that might be after the f2j jar was built, which defines our set.

I'm afraid it would be a large undertaking, with a large component devops, to rebuild everything off the latest LAPACK, so I could only look into this on a commercial basis. Perhaps a full week's work (the biggest difficulty is prepping cross platform build machines) going via #20

Rather than solve it directly like this, which is not scalable, I'd be far more interested in tackling it via #76 which would bring many additional benefits with it. That is more like 1 - 3 months.

**Comment by evolutics** [comment]
Thanks a lot for clarifying! I was not aware of all this complexity. And I thought that I may have just looked for `dpstrf` in the wrong place.

But not a problem – for now, I’ll probably just fall back on a general matrix decomposition like the LU decomposition.

**Comment by fommil** [comment]
OK, will close as a dupe then.
