### ISSUE TITLE
Provide staticly-linked mkl native libraries

### ISSUE THREAD

**Issue by eiennohito** [fommil/netlib-java#109]
Intel have created a [community license for MKL](https://registrationcenter.intel.com/en/forms/?productid=2558&licensetype=2) — basically free license without any support included. As far as I understand it, it is possible to distribute their redistributables.

So, it should be possible to provide builds of netlib-java native with MKL linked statically (done it locally, it works).

**Comment by fommil** [comment]
This doesn't look like a bug in `netlib-java`, it looks more like a support request for your machine.

Unfortunately I simply don't have the time to help out with these sorts of requests without a commercial contract in place. Most of the information that you need to solve this problem is available in the README and a seasoned GNU/Linux admin would be able to solve it for you. I'm not interested in making any more binary builds available for custom distributions.

If you'd be interested in sponsoring me to work on my `netlib-java` roadmap, to add support for additional native libraries or hardware (e.g. graphics cards and FPGAs) that is something I'd be interested in on a commercial basis. Please no time wasters: I'm not prepared to do any work on student rates, I am a professional developer and my day rate is in line with the London Scala contracting market in investment banking.
