### ISSUE TITLE
netlib-java is not support ARMV8(aarch64)

### ISSUE THREAD

**Issue by hengyuanzhi** [fommil/netlib-java#114]
Hello, fommil, I want to use netlib-java on  **ARMV8(aarch64)**, and use some blas library to accelerate our algorithm, but I found netlib-java is not support the architecture of ARMV8. Would you like to update netlib-java to support aarch64 these days? Your project is important for our application. If you are busy, can you teach me the way to let netlib-java support aarch64 ?

**Comment by fommil** [comment]
This doesn't look like a bug in `netlib-java`, it looks more like a support request for your machine.

Unfortunately I simply don't have the time to help out with these sorts of requests without a commercial contract in place. Most of the information that you need to solve this problem is available in the README and a seasoned GNU/Linux admin would be able to solve it for you. I'm not interested in making any more binary builds available for custom distributions.

If you'd be interested in getting your organisation to sponsor me to work on [the `netlib-java` roadmap](https://github.com/fommil/netlib-java/wiki/CallForFunding), to add support for additional native libraries or hardware (e.g. graphics cards and FPGAs) that is something I'd be interested in on a commercial basis.

**Comment by fommil** [comment]
https://github.com/fommil/netlib-java/pull/113 added support been I'm not planning on releasing binaries.
