### ISSUE TITLE
Support libgfortran.so.4

### ISSUE THREAD

**Issue by tutnixzursache** [fommil/netlib-java#124]
Hi,

Arch Linux  recently bumped the fortran runtime library to the next version and I assume that more distributions will follow over the next months.

Currently, Arch users can install libgfortran6 from the AUR, but that is not an optimal solution...

So in the long-term it might makes sense to support this newer version, too. 

P.s. I really like netlib-java (I'm using it through Breeze), thanks for the good work!

**Comment by fommil** [comment]
This doesn't look like a bug in `netlib-java`, it looks more like a support request for your machine.

Unfortunately I simply don't have the time to help out with these sorts of requests without a commercial contract in place. Most of the information that you need to solve this problem is available in the README and a seasoned GNU/Linux admin would be able to solve it for you. I'm not interested in making any more binary builds available for custom distributions.

If you'd be interested in getting your organisation to sponsor me to work on [the `netlib-java` roadmap](https://github.com/fommil/netlib-java/wiki/CallForFunding), to add support for additional native libraries or hardware (e.g. graphics cards and FPGAs) that is something I'd be interested in on a commercial basis.

**Comment by tutnixzursache** [comment]
Well, I would consider it is less a bug or feature request than a heads-up and I understand that for most people this is a non-issue right now. 

For myself, I've mitigated the problem using the above described solution (for Arch Linux). But, I assume more users will run into the same issue in the coming months:
 
As far as I've grasped the issue, the native components of netlib-java are compiled against the dynamic linked runtime libraries of gcc version 6.  However, I assume that  in the near future  more Linux distributions will drop support for GCC version 6 and its runtime libraries (i.e. among others libgfortran.so.3) and adopt GCC version 7 (stable since May 2017; shipping only libgfortran.so.4).
This means, that for those distributions---out of the box---only the fallback Java implementation would work, but not the native_ref/native_system versions (regardless of the underlying hardware architecture).

P.s. 
Regarding commercial sponsoring: Sorry, I'm just a student working with Scala Breeze on small university projects/homework. But I gladly buy you a cup of coffee or a bottle of beer in case we meet some day :-)

**Comment by fommil** [comment]
Thanks @tutnixzursache, I appreciate the offer. I've expected this for a long time and I have tried to warn the community.

The JVM implementation will always work, so nothing will break overnight for anybody. Commercial users of this library need to start supporting it properly. Perhaps this is the break that they need, I've been warning them for years.
