### ISSUE TITLE
Class not found exception in netlib-java

### ISSUE THREAD

**Issue by pushkarkrp** [fommil/netlib-java#126]
I am trying to use function "sgemm" from netlib-java,but when I try to run the code I get this exception saying
```

java.lang.NoClassDefFoundError: org/netlib/blas/Sgemm
	at org.netlib.blas.JBLAS.sgemm(JBLAS.java:267)
	at TBlas.main(TBlas.java:27)
Caused by: java.lang.ClassNotFoundException: org.netlib.blas.Sgemm
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```
	
when I looked into the netlib-java.jar following the path org/netlib/blas there is no class named "Sgemm"

Installed using the command: sudo apt-get install libnetlib-java
operating System:Ubuntu 16.0.4
Java-version:openjdk version "1.8.0_131"
netlib version:libnetlib 0.9.3

code is 

```
import org.netlib.blas.*;
public class TBlas {


    public static void main(String args[]) {
 
        float f1=1.0f;
        float f2=2.0f;
        float aa[]={1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f};
        float bb[]={1.0f,2.0f,3.0f,4.0f,5.0f,6.0f};
        float cc[]={1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f};
        BLAS a;
        a=BLAS.getInstance();
        a.sgemm( "N"  , "N"  , 6 , 4 , 5 , f1 , aa , 8 , bb , 6 , f2 , cc , 7 );
    }
}
```

**Comment by fommil** [comment]
This doesn't look like a bug in `netlib-java`, it looks more like a support request for your machine.

Unfortunately I simply don't have the time to help out with these sorts of requests without a commercial contract in place. Most of the information that you need to solve this problem is available in the README and a seasoned GNU/Linux admin would be able to solve it for you. I'm not interested in making any more binary builds available for custom distributions.

If you'd be interested in getting your organisation to sponsor me to work on [the `netlib-java` roadmap](https://github.com/fommil/netlib-java/wiki/CallForFunding), to add support for additional native libraries or hardware (e.g. graphics cards and FPGAs) that is something I'd be interested in on a commercial basis.
