### ISSUE TITLE
UnsatisfiedLinkError for dgemm_offsets

### ISSUE THREAD

**Issue by jmelot** [fommil/netlib-java#60]
Hello,

I'm running netlib-java through breeze. I specify this parameter:

-Dcom.github.fommil.netlib.NativeSystemBLAS.natives=my_blas_shared_object.so

where "my_blas_shared_object.so" is either the libblas.so that was already installed on my computer (in /usr/lib/libblas.so), or the one I get when I build OpenBLAS.

When I then do a matrix x matrix multiply between two Breeze DenseMatrixes, I get the following error:

Jan 30, 2014 11:14:00 AM com.github.fommil.jni.JniLoader liberalLoad
INFO: successfully loaded /home/jmelot/breeze-fwd-pass/OpenBLAS-master/libopenblasp-r0.2.8.so
java.lang.UnsatisfiedLinkError: com.github.fommil.netlib.NativeSystemBLAS.dgemm_offsets(Ljava/lang/String;Ljava/lang/String;IIID[DII[DIID[DII)V

If I do not specify com.github.fommil.netlib.NativeSystemBLAS.natives, netlib-java falls back to the reference blas implementation.

What I am running:

Ubuntu: Ubuntu 12.04.4 LTS x86_64
Java: 1.6.0_27
Breeze: 0.6-SNAPSHOT
Netlib: 1.1
OpenBLAS: 0.2.8 (latest release) and 0.2.9 (head in the develop branch)

I get this error when I build OpenBLAS with or without the parameters "NO_LAPACK=0" and "NO_CBLAS=0". 

Do you know what could be the problem? Thanks!

**Comment by nrigheriu** [comment]
> com.github.fommil.netlib.BLAS
<clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS 
>com.github.fommil.netlib.LAPACK <clinit>
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
I get this and other similar errors in Intellij when trying to run weka.classifiers.functions.LinearRegression. I'm running Ubuntu 16.04 and have libfortran3 installed (5.4.0-6ubuntu1~16.04.4). What could be causing this problem?

**Comment by fommil** [comment]
This doesn't look like a bug in `netlib-java`, it looks more like a support request for your machine.

Unfortunately I simply don't have the time to help out with these sorts of requests without a commercial contract in place. Most of the information that you need to solve this problem is available in the README and a seasoned GNU/Linux admin would be able to solve it for you. I'm not interested in making any more binary builds available for custom distributions.

If you'd be interested in getting your organisation to sponsor me to work on [the `netlib-java` roadmap](https://github.com/fommil/netlib-java/wiki/CallForFunding), to add support for additional native libraries or hardware (e.g. graphics cards and FPGAs) that is something I'd be interested in on a commercial basis.
