### ISSUE TITLE
How to use cuda on netlib-java?

### ISSUE THREAD

**Issue by sproblvem** [fommil/netlib-java#64]
Hi, I notice that you have test netlib-java on CudaBLAS, how did you do that?

I have a machine installed with [NVS-310](http://www.nvidia.com/object/nvs-310-graphics-card.html). And I run the example successfully:

```
$./matrixMulCUBLAS 
[Matrix Multiply CUBLAS] - Starting...
GPU Device 0: "NVS 310" with compute capability 2.1

MatrixA(320,640), MatrixB(320,640), MatrixC(320,640)
Computing result using CUBLAS...done.
Performance= 45.78 GFlop/s, Time= 2.863 msec, Size= 131072000 Ops
Computing result using host CPU...done.
Comparing CUBLAS Matrix Multiply with CPU results: PASS
```

I have tried to link the libblas.so.3 onto cublas.so directly but it didn't work, because of the symbol mismatching in the two libs. As follows:

```
$ ./run.sh blas2
[info] Loading project definition from /home/yama/mllib-accl/BreezeTest/project
[info] Set current project to RunMLLib (in build file:/home/yama/mllib-accl/BreezeTest/)
[info] Running BreezeTest blas2
Jun 11, 2014 8:02:23 PM com.github.fommil.jni.JniLoader liberalLoad
INFO: successfully loaded /tmp/jniloader4849024877314932027netlib-native_system-linux-x86_64.so
java: symbol lookup error: /tmp/jniloader4849024877314932027netlib-native_system-linux-x86_64.so: undefined symbol: cblas_dgemm
```

Looking for your reply!
Thank you.

**Comment by avulanov** [comment]
Hi! I was able to link cublas 6.0 to netlib-java linux native system wrapper. The performance of matrix multiplication was similar to openBlas for arrays up to 10K elements. For bigger arrays it was worse, probably due to the issues that you refer to in previous posts. Then I was told about BIDMat. It has Intel MKL blas and cublas via jcuda, as far as I understand. According to my tests, BIDMat's matrices multiplication is ~10x faster with cublas than with mkl blas. I also linked netlib-java with mkl blas and it was few times faster than openblas. To summarize the kind of matrices multiplication performance what I got: BIDMat jcuda >> BIDMat mkl ~= netlib-java-mkl>>netlib-java openblas>netlib-java cublas>f2jblas. Just in case, my tests are not statistically sound since they were done in few runs on one particular xeon machine (2.4) with particular geforce graphic card (gtx titan). So I would like to hear you opinion. Could you be so kind to comment what should be faster, jcuda with cublas or netlib-java with openblas (or mkl blas)?

**Comment by fommil** [comment]
Sweet! I've never heard of that setup before. If you're getting below "The Zone"  then you're definitely sharing memory between CPU and  GPU.  I'd planned to do something in this space but couldn't commercially justify it. I'm glad it has moved on. I'll have to read up on this library that you reference. If they are smart, they'll implement libblas.so. If they can't, they are cheating in the way described in my README

**Comment by avulanov** [comment]
Could you elaborate what do you mean by implementing libblas.so and cheating?

**Comment by fommil** [comment]
Watch my talk :smile:

If they can't implement libblas.so then they have some custom memory management that will only work for a small set of examples and will never be appropriate for arbitrary linear algebra. I hope they are using APU shared memory because that is the future.

**Comment by avulanov** [comment]
I've watched you talk the day before yesterday :smile: so I was able to understand "The Zone" term

However, I'm still confused by libblas.so and custom memory management. Could you please explain it in more details? Which particular APU do you refer to?

**Comment by fommil** [comment]
it is impossible to get faster than MKL using the traditional CPU memory region. If they are using the GPU then they are using the GPU memory region: which means they can't implement libblas.so because libblas.so takes pointers to the CPU memory region. They could, however, be getting a performance benefit by "cheating" and only using GPU memory, they won't be including copying memory to/from the GPU region, which is absolutely necessary to get any results out of the computations.

**Comment by avulanov** [comment]
Thanks for explanation! Indeed, it would be interesting to know if they copy the result or not. If not, I think it is still OK because they can run the whole algorithm on GPU given that it computes much faster than CPU. 

In the meantime, I was finally able to make additional performance comparisons. It turns out that: 
BIDMat-cublas>>BIDMat MKL==netlib-mkl==netlib-openblas-compiled>netlib-openblas-yum-repo>netlib-cublas=netlib-blas>f2jblas

Just in case, below is the link to the spreadsheet with full results. 
https://docs.google.com/spreadsheets/d/1lWdVSuSragOobb0A_oeouQgHUMx378T9J5r7kwKSPkY/edit?usp=sharing

**Comment by fommil** [comment]
if you can write your entire algorithm to run in the GPU so that you only copy in the setup and copy back the result, that's probably going to give you the best performance. That means not using BLAS/LAPACK (for the reasons discussed above) so it is certainly less portable.

I really hope that APUs fix this and in which case you'll find that netlib-java with MultiBLAS (using dual MKL/GPU backends) will win every race :wink: That won't even require you to update your netlib-java installation.

**Comment by fommil** [comment]
@avulanov btw, locally compiling OpenBLAS won't give you a performance speedup. It is assembly code so doesn't tune itself. You're thinking of ATLAS (I admit, my own README doesn't help clear this up... I should rewrite it). Ditto, MKL (which is proprietary anyway).

**Comment by fommil** [comment]
@avulanov btw, how did you do `netlib-cublas` ?? I'm not aware of a `libblas.so.3` that is provided by cuBLAS. It would be very interesting if there is one!

**Comment by avulanov** [comment]
I observed almost 5x speedup for locally compiled OpenBlas versus OpenBlas installed from Fedora repo. It performed almost as MLK. One of the reasons might be that it has optimizations for different CPU families, see https://github.com/xianyi/OpenBLAS/blob/develop/TargetList.txt. Probably during the compilation it assembled for my CPU specifically versus the generic assembly from repo. Does it makes sense to you?

Regarding `netlib-cublas`, I changed the linker option in `native_system/xbuilds/linux-x64_86/pom.xml` from `-lblas` to `-lcublas` and added the linker path option `-L/usr/local/cuda/lib64` so it was able to find the library. The same way `mkl` and `openblas` linking was done.

**Comment by fommil** [comment]
oh, it might be a version thing. Was the pre-installed version of OpenBLAS version perhaps lacking your CPU instructions?

Re: cublas I don't see how that would work. libcublas is not BLAS... it is BLAS-like. Unless they recently released a **real** BLAS implementation. Check that JNILoader didn't just bail.

BTW, I don't know why you're building netlib-java for this. You just need to change the library at runtime... have a read of the README again because you're doing far too much work.

**Comment by EmergentOrder** [comment]
@fommil I think you've already been introduced recently based on the spark-dev mailing lists, but you should definitely consider using NVBLAS here. It is a full, drop-in BLAS replacement, available since CUDA 6.0. See my never-merged [due to project stagnation] PR here: https://github.com/mikiobraun/jblas/pull/47 . Not entirely sure, but I think the default is it forwards only BLAS level 3, size 10,000 or higher to cuBLAS. Doc here: http://on-demand.gputechconf.com/supercomputing/2013/presentation/SC3108-New-Features-CUDA%206%20-GPU-Acceleration.pdf 
claims : "Optionally configure which routines and matrix sizes are accelerated" 
although I don't see the size setting in the official doc here: http://docs.nvidia.com/cuda/nvblas/index.html#NVBLAS_CONFIG_FILE

**Comment by EmergentOrder** [comment]
In the context of this project it seems like the most appropriate place might be the README. 
Side note: I'm planning on checking out your talk.

**Comment by fommil** [comment]
@EmergentOrder I don't need to use anything specific in netlib-java, you can swap `libblas` implementations at runtime.

**Comment by avulanov** [comment]
nvblas functions should replace current blas functions calls after executing LD_PRELOAD as suggested in http://docs.nvidia.com/cuda/nvblas/#Usage without any changes to netlib-java.

**Comment by EmergentOrder** [comment]
Thanks guys. I did realize this, I just meant it might be nice to mention that this is possible in the README.
