### ISSUE TITLE
Runtime error with homebrew netlib-native_system-linux-x86_64-natives.jar on CentOS 7.0

### ISSUE THREAD

**Issue by yangliuyu** [fommil/netlib-java#66]
Hi, 

I got a runtime error when running spark application. 

/usr/java/jdk1.7.0_65/bin/java: symbol lookup error: /tmp/jniloader9104995036364593011netlib-native_system-linux-x86_64.so: undefined symbol: cblas_daxpy

[Build steps](https://gist.github.com/yangliuyu/59416361d4b3a413be49)

Same build steps work on CentOs 6.5, so maybe it caused by the library version.

gcc.x86_64                       4.8.2-16.el7                          @base
gcc-gfortran.x86_64              4.8.2-16.el7                          @base
libgfortran.x86_64               4.8.2-16.el7                          @base
blas.x86_64                      3.4.2-4.el7                           @base
lapack.x86_64                    3.4.2-4.el7                           @base
arpack.x86_64                    3.1.3-2.el7                           @epel

**Comment by gabeos** [comment]
I ran into this same issue -- in Fedora 21 atlas is packaged only with libsatlas.so (serial) and libtatlas.so (threaded)
[Errant bug report describing change](https://bugzilla.redhat.com/show_bug.cgi?id=1174259)

There's an apparently ongoing discussion of how to handle this [here](https://fedorahosted.org/fpc/ticket/352)

Anyway, now with fedora 21, you can't downgrade to atlas 3.8, so there's no easy way to get things working. I force installed an old rpm of 3.8 with 'rpm' rather than yum/dnf, but it's super hacky and might very well break things..

anyway, I'm just wondering if you have any other suggestions, is there a way to build netlib-java or otherwise directly specify with libraries to use? I tried making symlinks to the libsatlas.so library in the /lib64/atlas directory (same error).

**Comment by fommil** [comment]
yeah, unfortunately the only thing I can recommend is to tell Fedora to learn how to package these projects correctly.

You could try installing the debian/ubuntu equivalents.

You don't need to recompile netlib-java. You just need to link it to a library at runtime that implements libblas.so.3 and liblapack.so.3 through symlinks.

Try OpenBLAS or Intel's Math Kernel Library. They are faster anyway.

**Comment by kgrech** [comment]
Same issue for openSuse 13.1. Solved by removing repository version of atlas and installing the following rpm:
http://rpm.pbone.net/index.php3/stat/4/idpl/23733523/dir/opensuse/com/atlas-3.8.3-5.1.x86_64.rpm.html

**Comment by danielkza** [comment]
Sorry for reviving this old issue, but it seems as of today Fedora still does not ship CBLAS with ATLAS or OpenBLAS. There seems to be an implementation available from GSL in `libgslcblas.so.0`. My first try was to simply symlink it to `libcblas.so.3`, but it was not sufficient, as it seems the netlib JNI objects are not compiled with `-lcblas`.

The only solution that seemed to work was to run Java with `LD_PRELOAD=libgslcblas.so.0` in it's environment, so that the CBLAS symbols are already loaded in the JVM when netlib-native is loaded. Unfortunately I don't see an easy way to construct a library that would work in both situations, as explicitly linking to CBLAS would break Debian-based distributions, which do not have it.

**Comment by fommil** [comment]
GSL is GPL. Make sure that your application is correctly licensed GPL if distributing them linked to GSL.

**Comment by danielkza** [comment]
I'm not distributing any binaries with the LD_PRELOAD workaround applied, I only used it privately. I thought it might be useful to anyone ending up in this thread from Google.
