### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by xhudik** [fommil/netlib-java#73]
Hi, I was trying to compile your library by
mvn clean package

and got an error:
[ERROR] Plugin com.github.fommil.netlib:generator:1.2-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact com.github.fommil.netlib:generator:jar:1.2-SNAPSHOT in sonatype-plugins-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]

Looks like some dependency/version mistake...

Any idea?

Thanks, Tomas

**Comment by xhudik** [comment]
thanks fommil for the fast answer!

I do have an additional question:
does netlib-java have any verbosity/logging switch?

Basically, my problem is that I always get error message:
_BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS_

Even i have successfully installed openBlas and make ln -s  /usr/local/lib/libopenblas.so libblas.so.3. Therefore some more logs would be welcome...

thanks, Tomas

**Comment by fommil** [comment]
This is through the standard logging framework. Learn how to do this via the Java Util Logging API (or use the JUL backend to SLF4J).

Unfortunately it is not possible to get any more fine grained detail than "it failed to load" because it's all happening in the native layer. You could try extracting the relevant netlib-java `.so` and doing an `ldd` on it to see which libs it is linking to.
