### ISSUE TITLE
Add csparse, amd and ldl to Netlib-java

### ISSUE THREAD

**Issue by debasish83** [fommil/netlib-java#77]
I have created and used the jni library out of amd and ldl but it will be great if they can be integrated in netlib-java compilation so that we can use it in Spark and Breeze projects.
https://github.com/embotech/ecos/pull/88

The license is lgpl and I was not sure if it is fine to put lgpl code in netlib ? Even inside Spark I see netlib profile as a lgpl license...

csparse license might be ok but I already see netlib BLAS has been used in Spark BLAS for sparse operations

**Comment by fommil** [comment]
Apache don't let us use LGPL, so I've had to make the native parts optional. 

Sorry, this would upset Apache too much (who are doing this for political reasons... LGPL is far superior to Apache License) 

Can you please add a link to the libraries you're talking about? I'm not sure it would make sense to pull in other Java libraries because applications can just pull them in if they need them  anyway.

**Comment by fommil** [comment]
Btw MTJ in LGPL so if you have a faster alternative for some solver, you could put it there!

**Comment by debasish83** [comment]
This is the library: http://faculty.cse.tamu.edu/davis/suitesparse.html We used in ECOS...
It is not possible to add this in native part of netlib-java ? Since you already have a JNI flow, I would like to reuse it rather than adding another JNI flow

**Comment by debasish83** [comment]
Also personally I am anyway compiling with native netlib flag for dgemm and blocked matrix operations :-)...

**Comment by fommil** [comment]
The build pipeline for netlib-java is incredibly complex, due to the lack of cross-compilers for fortran.

Even for other native libraries, I'm going to create separate projects. The goal of netlib-java is really just the netlib.org libraries onto the JVM.

re: "compiling with native netlib flag", what do you mean? Please watch my talk, linked from the main page, for more details on why "system optimised" is far superior to the "native" libs. Also, I trust that you're not actually recompiling netlib-java.

**Comment by debasish83** [comment]
Not recompiling but compiling Spark with -Pnetlib-lgpl...Let me look into the talk...I am not using any native libs if I compile spark with -Pnetlib-lgpl and use dgemm from BLAS ? It will fall back to my system's BLAS ?

**Comment by fommil** [comment]
@debasish83 also reread the spark docs on this area. I updated them very recently. The spark guys were a bit confused with the details :-)

**Comment by fommil** [comment]
@debasish83  https://github.com/apache/spark/blob/0cba802adf15f5ab8da24dd1e8a5e7214cc4e148/docs/mllib-guide.md#dependencies

**Comment by debasish83** [comment]
I got it...netlib-java is for netlib library...Could you point me to the code where you make sure within JVM and Native no array copies are done ? I think I did not optimize on that aspect and my JNI implementation was slower...But it was not bad

**Comment by fommil** [comment]
watch my talk

**Comment by debasish83** [comment]
watching it :-)

**Comment by debasish83** [comment]
Thanks I got what I was looking for http://fommil.github.io/scalax14/#/9/6 :-) My JNI implementation was crap and doing all sort of copies I think...no wonder it was slow !
https://github.com/debasish83/ecos/blob/master/src/main/native/NativeECOS.c

**Comment by fommil** [comment]
just using the fortran compiled blas/lapack is still going to be crap, you need to set up MJL or OpenBLAS to get real performance.

**Comment by debasish83** [comment]
Got it...Let me set it up for OpenBLAS...
